/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.examenp2_luismontalvan;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author luism
 */
public class CRUDComputadoras extends javax.swing.JFrame {
    ArrayList<Computadora> computadoras = new ArrayList();
    String host1 = "";
    String ip = "";
    String mask = "";
    /**
     * Creates new form CRUDComputadoras
     */
    public CRUDComputadoras() {
        initComponents();
        jPanelEscritorio.setVisible(false);
        jPanelLaptop.setVisible(false);
        jPanelAgregar.setVisible(false);
        jPanelListarTabla.setVisible(false);
        jPanelEliminar.setVisible(false);
        jPanelTipoPC.setVisible(false);
        jPanelListar.setVisible(false);
        jPanelEliminarPC.setVisible(false);
        jPanelComputadoraAgregar.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        Background = new javax.swing.JPanel();
        jPanelVacio2 = new javax.swing.JPanel();
        jPanelVacio = new javax.swing.JPanel();
        jPanelIngresarPC = new javax.swing.JPanel();
        jPanelComputadoraAgregar = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTFHost = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTFIP = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTFMask = new javax.swing.JTextField();
        BtnSiguiente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jCBIngresar = new javax.swing.JComboBox<>();
        BtnIngresarPC = new javax.swing.JButton();
        jPanelTipoPC = new javax.swing.JPanel();
        BtnEscritorio = new javax.swing.JButton();
        BtnLaptop = new javax.swing.JButton();
        jPanelHoriz = new javax.swing.JPanel();
        BtnAgregar = new javax.swing.JButton();
        BtnListar = new javax.swing.JButton();
        BtnElimiar = new javax.swing.JButton();
        BtnIngresar = new javax.swing.JButton();
        jPanelAgregar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelListar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelEliminar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelIngresar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanelEscritorio = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTFRam = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFStorage = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jCBTypeStrorage = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jCBGPU = new javax.swing.JComboBox<>();
        BtnAgregarPC = new javax.swing.JButton();
        jPanelListarTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelEliminarPC = new javax.swing.JPanel();
        jCBEliminar = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        BtnEliminarPC = new javax.swing.JButton();
        PanelIngresar = new javax.swing.JPanel();
        jPanelLaptop = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTFMarca = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTFResolution = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jCBRGB = new javax.swing.JComboBox<>();
        BtnAgregarLaptop = new javax.swing.JButton();

        jLabel6.setText("jLabel1");

        jTextField1.setText("jTextField1");

        jLabel15.setText("jLabel14");

        jTextField3.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(0, 0, 0));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanelVacio2Layout = new javax.swing.GroupLayout(jPanelVacio2);
        jPanelVacio2.setLayout(jPanelVacio2Layout);
        jPanelVacio2Layout.setHorizontalGroup(
            jPanelVacio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelVacio2Layout.setVerticalGroup(
            jPanelVacio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        Background.add(jPanelVacio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelVacio.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanelVacioLayout = new javax.swing.GroupLayout(jPanelVacio);
        jPanelVacio.setLayout(jPanelVacioLayout);
        jPanelVacioLayout.setHorizontalGroup(
            jPanelVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanelVacioLayout.setVerticalGroup(
            jPanelVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Background.add(jPanelVacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 550, -1));

        javax.swing.GroupLayout jPanelIngresarPCLayout = new javax.swing.GroupLayout(jPanelIngresarPC);
        jPanelIngresarPC.setLayout(jPanelIngresarPCLayout);
        jPanelIngresarPCLayout.setHorizontalGroup(
            jPanelIngresarPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelIngresarPCLayout.setVerticalGroup(
            jPanelIngresarPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );

        Background.add(jPanelIngresarPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel14.setText("Host");

        jTFHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFHostActionPerformed(evt);
            }
        });

        jLabel16.setText("IP");

        jLabel17.setText("Mask");

        jTFMask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFMaskActionPerformed(evt);
            }
        });

        BtnSiguiente.setText("Siguiente");
        BtnSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSiguienteMouseClicked(evt);
            }
        });

        jLabel18.setText("Computadora a ingresar");

        jCBIngresar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        BtnIngresarPC.setText("Ingresar");
        BtnIngresarPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarPCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jCBIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(BtnIngresarPC, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnIngresarPC, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelComputadoraAgregarLayout = new javax.swing.GroupLayout(jPanelComputadoraAgregar);
        jPanelComputadoraAgregar.setLayout(jPanelComputadoraAgregarLayout);
        jPanelComputadoraAgregarLayout.setHorizontalGroup(
            jPanelComputadoraAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComputadoraAgregarLayout.createSequentialGroup()
                .addGroup(jPanelComputadoraAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelComputadoraAgregarLayout.createSequentialGroup()
                        .addGap(523, 523, 523)
                        .addGroup(jPanelComputadoraAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFHost, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFIP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFMask, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelComputadoraAgregarLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(BtnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelComputadoraAgregarLayout.setVerticalGroup(
            jPanelComputadoraAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComputadoraAgregarLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFMask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Background.add(jPanelComputadoraAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 500, 420));

        jPanelTipoPC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnEscritorio.setText("Escritorio");
        BtnEscritorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEscritorioMouseClicked(evt);
            }
        });
        BtnEscritorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEscritorioActionPerformed(evt);
            }
        });
        jPanelTipoPC.add(BtnEscritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 84, 200, 101));

        BtnLaptop.setText("Laptop");
        BtnLaptop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLaptopMouseClicked(evt);
            }
        });
        BtnLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLaptopActionPerformed(evt);
            }
        });
        jPanelTipoPC.add(BtnLaptop, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 240, 200, 99));

        Background.add(jPanelTipoPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 500, 420));

        jPanelHoriz.setBackground(new java.awt.Color(0, 0, 204));

        BtnAgregar.setText("Agregar Computadora");
        BtnAgregar.setMaximumSize(new java.awt.Dimension(250, 50));
        BtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAgregarMouseClicked(evt);
            }
        });
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        BtnListar.setText("Listar");
        BtnListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnListarMouseClicked(evt);
            }
        });

        BtnElimiar.setText("Eliminar Computadora");
        BtnElimiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnElimiarMouseClicked(evt);
            }
        });
        BtnElimiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnElimiarActionPerformed(evt);
            }
        });

        BtnIngresar.setText("Ingresar Computadora");
        BtnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnIngresarMouseClicked(evt);
            }
        });
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHorizLayout = new javax.swing.GroupLayout(jPanelHoriz);
        jPanelHoriz.setLayout(jPanelHorizLayout);
        jPanelHorizLayout.setHorizontalGroup(
            jPanelHorizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHorizLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelHorizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnElimiar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelHorizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BtnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(BtnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(140, 140, 140))
        );
        jPanelHorizLayout.setVerticalGroup(
            jPanelHorizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHorizLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(BtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnElimiar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        Background.add(jPanelHoriz, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 520));

        jPanelAgregar.setBackground(new java.awt.Color(0, 0, 204));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Agregar COmputadora");
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 30));

        javax.swing.GroupLayout jPanelAgregarLayout = new javax.swing.GroupLayout(jPanelAgregar);
        jPanelAgregar.setLayout(jPanelAgregarLayout);
        jPanelAgregarLayout.setHorizontalGroup(
            jPanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgregarLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addGap(108, 108, 108))
        );
        jPanelAgregarLayout.setVerticalGroup(
            jPanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgregarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );

        Background.add(jPanelAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 550, -1));

        jPanelListar.setBackground(new java.awt.Color(0, 0, 204));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Listar");
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 30));

        javax.swing.GroupLayout jPanelListarLayout = new javax.swing.GroupLayout(jPanelListar);
        jPanelListar.setLayout(jPanelListarLayout);
        jPanelListarLayout.setHorizontalGroup(
            jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addGap(108, 108, 108))
        );
        jPanelListarLayout.setVerticalGroup(
            jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );

        Background.add(jPanelListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 550, -1));

        jPanelEliminar.setBackground(new java.awt.Color(0, 0, 204));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Agregar Computadora");
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 30));

        javax.swing.GroupLayout jPanelEliminarLayout = new javax.swing.GroupLayout(jPanelEliminar);
        jPanelEliminar.setLayout(jPanelEliminarLayout);
        jPanelEliminarLayout.setHorizontalGroup(
            jPanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEliminarLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addGap(108, 108, 108))
        );
        jPanelEliminarLayout.setVerticalGroup(
            jPanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEliminarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );

        Background.add(jPanelEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 550, -1));

        jPanelIngresar.setBackground(new java.awt.Color(0, 0, 204));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ingresar a Computadora");
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 30));

        javax.swing.GroupLayout jPanelIngresarLayout = new javax.swing.GroupLayout(jPanelIngresar);
        jPanelIngresar.setLayout(jPanelIngresarLayout);
        jPanelIngresarLayout.setHorizontalGroup(
            jPanelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIngresarLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addGap(108, 108, 108))
        );
        jPanelIngresarLayout.setVerticalGroup(
            jPanelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIngresarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );

        Background.add(jPanelIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 550, -1));

        jLabel7.setText("Ram");

        jLabel8.setText("Almacenamiento");

        jLabel9.setText("Tipo de almacenamiento");

        jCBTypeStrorage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HDD", "SSD"}));

        jLabel10.setText("Tarjeta Grafica");

        jCBGPU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No"}));

        BtnAgregarPC.setText("Agregar");
        BtnAgregarPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAgregarPCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelEscritorioLayout = new javax.swing.GroupLayout(jPanelEscritorio);
        jPanelEscritorio.setLayout(jPanelEscritorioLayout);
        jPanelEscritorioLayout.setHorizontalGroup(
            jPanelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEscritorioLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFRam)
                    .addComponent(jTFStorage)
                    .addComponent(jCBTypeStrorage, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCBGPU, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelEscritorioLayout.createSequentialGroup()
                        .addGroup(jPanelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addGap(247, 247, 247))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEscritorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnAgregarPC, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );
        jPanelEscritorioLayout.setVerticalGroup(
            jPanelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEscritorioLayout.createSequentialGroup()
                .addContainerGap(257, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFStorage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBTypeStrorage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBGPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnAgregarPC, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );

        Background.add(jPanelEscritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 500, 420));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanelListarTablaLayout = new javax.swing.GroupLayout(jPanelListarTabla);
        jPanelListarTabla.setLayout(jPanelListarTablaLayout);
        jPanelListarTablaLayout.setHorizontalGroup(
            jPanelListarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        jPanelListarTablaLayout.setVerticalGroup(
            jPanelListarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListarTablaLayout.createSequentialGroup()
                .addGap(0, 71, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Background.add(jPanelListarTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 500, 420));

        jCBEliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        jCBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBEliminarActionPerformed(evt);
            }
        });

        jLabel1.setText("Computadora a Eliminar");

        BtnEliminarPC.setText("Eliminar");
        BtnEliminarPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEliminarPCMouseClicked(evt);
            }
        });
        BtnEliminarPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarPCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEliminarPCLayout = new javax.swing.GroupLayout(jPanelEliminarPC);
        jPanelEliminarPC.setLayout(jPanelEliminarPCLayout);
        jPanelEliminarPCLayout.setHorizontalGroup(
            jPanelEliminarPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEliminarPCLayout.createSequentialGroup()
                .addGroup(jPanelEliminarPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEliminarPCLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanelEliminarPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanelEliminarPCLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(BtnEliminarPC, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanelEliminarPCLayout.setVerticalGroup(
            jPanelEliminarPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEliminarPCLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnEliminarPC, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        Background.add(jPanelEliminarPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 500, 420));

        javax.swing.GroupLayout PanelIngresarLayout = new javax.swing.GroupLayout(PanelIngresar);
        PanelIngresar.setLayout(PanelIngresarLayout);
        PanelIngresarLayout.setHorizontalGroup(
            PanelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        PanelIngresarLayout.setVerticalGroup(
            PanelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        Background.add(PanelIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 500, 420));

        jLabel11.setText("Marca");

        jLabel12.setText("Definicion de Pantalla");

        jLabel13.setText("RGB");

        jCBRGB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        BtnAgregarLaptop.setText("Agregar");
        BtnAgregarLaptop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAgregarLaptopMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelLaptopLayout = new javax.swing.GroupLayout(jPanelLaptop);
        jPanelLaptop.setLayout(jPanelLaptopLayout);
        jPanelLaptopLayout.setHorizontalGroup(
            jPanelLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLaptopLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanelLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFMarca)
                    .addComponent(jTFResolution)
                    .addComponent(jCBRGB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelLaptopLayout.createSequentialGroup()
                        .addGroup(jPanelLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap(274, Short.MAX_VALUE))
            .addGroup(jPanelLaptopLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(BtnAgregarLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLaptopLayout.setVerticalGroup(
            jPanelLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLaptopLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFResolution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBRGB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnAgregarLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        Background.add(jPanelLaptop, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 500, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnIngresarActionPerformed

    private void BtnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregarMouseClicked
        
        jPanelComputadoraAgregar.setVisible(true);
        
        
    }//GEN-LAST:event_BtnAgregarMouseClicked

    private void BtnListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnListarMouseClicked
        String s = "";
        for (Object t : computadoras) {
            s = computadoras.get((Integer)t)+") "+t +"\n";
            
        }
        JOptionPane.showMessageDialog(null, s);
    }//GEN-LAST:event_BtnListarMouseClicked

    private void BtnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIngresarMouseClicked
        
    }//GEN-LAST:event_BtnIngresarMouseClicked

    private void BtnElimiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnElimiarMouseClicked
        jPanelEliminarPC.setVisible(true);
    }//GEN-LAST:event_BtnElimiarMouseClicked

    private void BtnElimiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnElimiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnElimiarActionPerformed

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void BtnLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLaptopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnLaptopActionPerformed

    private void BtnEscritorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEscritorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEscritorioActionPerformed

    private void BtnEscritorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEscritorioMouseClicked
        jPanelTipoPC.setVisible(false);
        jPanelEscritorio.setVisible(true);
    }//GEN-LAST:event_BtnEscritorioMouseClicked

    private void BtnLaptopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLaptopMouseClicked
        jPanelTipoPC.setVisible(false);
        jPanelLaptop.setVisible(true);
    }//GEN-LAST:event_BtnLaptopMouseClicked

    private void BtnAgregarPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregarPCMouseClicked
        computadoras.add(new Escritorio()); 
        int pos = computadoras.size()-1;
        ((Escritorio)computadoras.get(pos)).setHost(host1);
        ((Escritorio)computadoras.get(pos)).setIp(ip);
        ((Escritorio)computadoras.get(pos)).setMask(mask);
        ((Escritorio)computadoras.get(pos)).setRam(String.valueOf(jTFRam.getText()));
        ((Escritorio)computadoras.get(pos)).setStorage(String.valueOf(jTFStorage.getText()));
        ((Escritorio)computadoras.get(pos)).setTypeStorage(String.valueOf(jCBTypeStrorage.getSelectedItem()));
        ((Escritorio)computadoras.get(pos)).setResp(String.valueOf(jCBGPU.getSelectedItem()));
        jCBEliminar.addItem(host1);
        jCBIngresar.addItem(host1);
        JOptionPane.showMessageDialog(null, "La computadora se agrego con exito");
        jPanelEscritorio.setVisible(false);
    }//GEN-LAST:event_BtnAgregarPCMouseClicked

    private void jTFHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFHostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFHostActionPerformed

    private void jTFMaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFMaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFMaskActionPerformed

    private void BtnSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSiguienteMouseClicked
        host1 = String.valueOf(jTFHost.getText());
        ip = String.valueOf(jTFIP.getText());
        mask = String.valueOf(jTFMask.getText());
        jPanelComputadoraAgregar.setVisible(false);
        jPanelTipoPC.setVisible(true);
    }//GEN-LAST:event_BtnSiguienteMouseClicked

    private void BtnAgregarLaptopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregarLaptopMouseClicked
        jPanelLaptop.setVisible(true);
        
        computadoras.add(new Laptop());  
        int pos = computadoras.size()-1;
        ((Laptop)computadoras.get(pos)).setHost(host1);
        ((Laptop)computadoras.get(pos)).setIp(ip);
        ((Laptop)computadoras.get(pos)).setMask(mask);
        ((Laptop)computadoras.get(pos)).setResolution(String.valueOf(jTFResolution.getText()));
        ((Laptop)computadoras.get(pos)).setMarca(String.valueOf(jTFMarca.getText()));
        ((Laptop)computadoras.get(pos)).setResp(String.valueOf(jCBRGB.getSelectedItem()));
        jCBEliminar.addItem(host1);
        jCBIngresar.addItem(host1);
        JOptionPane.showMessageDialog(null, "La computadora se agrego con exito");
        jPanelLaptop.setVisible(false);
    }//GEN-LAST:event_BtnAgregarLaptopMouseClicked

    private void jCBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBEliminarActionPerformed

    private void BtnEliminarPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEliminarPCActionPerformed

    private void BtnEliminarPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarPCMouseClicked
        int pos = jCBEliminar.getSelectedIndex();
        computadoras.remove(pos);
        jCBEliminar.removeItemAt(pos);
        jCBIngresar.removeItemAt(pos);
    }//GEN-LAST:event_BtnEliminarPCMouseClicked

    private void BtnIngresarPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnIngresarPCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDComputadoras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDComputadoras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDComputadoras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDComputadoras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDComputadoras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnAgregarLaptop;
    private javax.swing.JButton BtnAgregarPC;
    private javax.swing.JButton BtnElimiar;
    private javax.swing.JButton BtnEliminarPC;
    private javax.swing.JButton BtnEscritorio;
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JButton BtnIngresarPC;
    private javax.swing.JButton BtnLaptop;
    private javax.swing.JButton BtnListar;
    private javax.swing.JButton BtnSiguiente;
    private javax.swing.JPanel PanelIngresar;
    private javax.swing.JComboBox<String> jCBEliminar;
    private javax.swing.JComboBox<String> jCBGPU;
    private javax.swing.JComboBox<String> jCBIngresar;
    private javax.swing.JComboBox<String> jCBRGB;
    private javax.swing.JComboBox<String> jCBTypeStrorage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAgregar;
    private javax.swing.JPanel jPanelComputadoraAgregar;
    private javax.swing.JPanel jPanelEliminar;
    private javax.swing.JPanel jPanelEliminarPC;
    private javax.swing.JPanel jPanelEscritorio;
    private javax.swing.JPanel jPanelHoriz;
    private javax.swing.JPanel jPanelIngresar;
    private javax.swing.JPanel jPanelIngresarPC;
    private javax.swing.JPanel jPanelLaptop;
    private javax.swing.JPanel jPanelListar;
    private javax.swing.JPanel jPanelListarTabla;
    private javax.swing.JPanel jPanelTipoPC;
    private javax.swing.JPanel jPanelVacio;
    private javax.swing.JPanel jPanelVacio2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFHost;
    private javax.swing.JTextField jTFIP;
    private javax.swing.JTextField jTFMarca;
    private javax.swing.JTextField jTFMask;
    private javax.swing.JTextField jTFRam;
    private javax.swing.JTextField jTFResolution;
    private javax.swing.JTextField jTFStorage;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
    
}
